const cityData={
 home:{icon:'🏠',name:'Homes',cost:180000,pop:1000,edu:0,health:0,safety:0,happy:2},
 school:{icon:'🏫',name:'School',cost:240000,pop:0,edu:28,health:0,safety:0,happy:4},
 hospital:{icon:'🏥',name:'Hospital',cost:320000,pop:0,edu:0,health:32,safety:3,happy:5},
 park:{icon:'🌳',name:'Park',cost:90000,pop:0,edu:0,health:4,safety:0,happy:18},
 fire:{icon:'🚒',name:'Fire Station',cost:210000,pop:0,edu:0,health:0,safety:30,happy:4},
 bus:{icon:'🚌',name:'Bus Hub',cost:160000,pop:0,edu:2,health:0,safety:2,happy:10},
 shop:{icon:'🛒',name:'Shops',cost:120000,pop:0,edu:0,health:0,safety:0,happy:8}
};
const SAVE_KEY='cw_city_builder_v2';
let budget=2000000,selected=null,placements=[],history=[],completionRewarded=false;const board=document.getElementById('cityBoard');
function loadCity(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(s&&Array.isArray(s.placements)){budget=Number(s.budget)||2000000;placements=s.placements;completionRewarded=!!s.completionRewarded;document.getElementById('cityInstruction').textContent='Saved city restored. Keep building or reset to start again.'}}catch(e){}}
function saveCity(){localStorage.setItem(SAVE_KEY,JSON.stringify({budget,placements,completionRewarded,updatedAt:Date.now()}));if(window.CWState){const used=placements.filter(Boolean).length;CWState.setProgress('citybuilder',completionRewarded?100:Math.min(95,Math.round(used/12*100)),{budget,plots:used});if(!completionRewarded)CWState.setResume({id:'citybuilder',title:'Build Your City',icon:'🏙️',href:'city-builder.html',kind:'Build'})}}
loadCity();
for(let i=0;i<30;i++){const cell=document.createElement('button');cell.className='city-cell';cell.dataset.index=i;cell.setAttribute('aria-label','Empty city plot');cell.addEventListener('click',()=>place(selected,i));cell.addEventListener('dragover',e=>e.preventDefault());cell.addEventListener('drop',e=>{e.preventDefault();place(e.dataTransfer.getData('text/plain'),i)});board.appendChild(cell)}
document.querySelectorAll('.building-tool').forEach(b=>{b.onclick=()=>{selected=b.dataset.type;document.querySelectorAll('.building-tool').forEach(x=>x.classList.toggle('selected',x===b));document.getElementById('cityInstruction').textContent=`Selected ${cityData[selected].name}. Tap an empty plot.`};b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',b.dataset.type))});
function place(type,index){if(!type)return;if(placements[index]){document.getElementById('cityEvent').innerHTML='<b>City Adviser</b><p>That plot is already occupied. Choose another one.</p>';return}const d=cityData[type];if(budget<d.cost){document.getElementById('cityEvent').innerHTML='<b>Budget Alert</b><p>You cannot afford that building. Re-think your plan or undo something.</p>';playTone(false);return}history.push(JSON.stringify({budget,placements}));budget-=d.cost;placements[index]=type;render();saveCity();if(placements.filter(Boolean).length===7)document.getElementById('cityEvent').innerHTML='<b>City Event</b><p>Traffic is increasing. Public transport and green space can improve the city rating.</p>'}
function totals(){let t={pop:0,edu:0,health:0,safety:0,happy:0};placements.filter(Boolean).forEach(x=>{const d=cityData[x];t.pop+=d.pop;t.edu+=d.edu;t.health+=d.health;t.safety+=d.safety;t.happy+=d.happy});return t}
function render(){[...board.children].forEach((cell,i)=>{const type=placements[i];cell.innerHTML=type?`<span>${cityData[type].icon}</span><small>${cityData[type].name}</small>`:'<i>+</i>';cell.classList.toggle('filled',!!type)});const t=totals();document.getElementById('budget').textContent='£'+budget.toLocaleString('en-GB');document.getElementById('population').textContent=t.pop.toLocaleString();document.getElementById('education').textContent=Math.min(100,t.edu);document.getElementById('health').textContent=Math.min(100,t.health);document.getElementById('safetyScore').textContent=Math.min(100,t.safety);document.getElementById('happiness').textContent=Math.min(100,t.happy);const has=k=>placements.includes(k);const checks={population:t.pop>=5000,school:has('school'),hospital:has('hospital'),park:has('park'),fire:has('fire'),bus:has('bus'),budget:budget>=0};document.querySelectorAll('#objectiveList li').forEach(li=>{const ok=checks[li.dataset.key];li.classList.toggle('done',ok);li.textContent=(ok?'✅':'⬜')+' '+li.textContent.replace(/^[⬜✅]\s*/,'')});let score=0;Object.values(checks).forEach(v=>score+=v?12:0);score+=Math.min(16,Math.round((Math.min(100,t.edu)+Math.min(100,t.health)+Math.min(100,t.safety)+Math.min(100,t.happy))/25));score=Math.min(100,score);document.getElementById('rating').textContent=score;const win=Object.values(checks).every(Boolean);document.getElementById('missionState').textContent=win?'MISSION COMPLETE':'IN PROGRESS';if(win){document.getElementById('cityEvent').innerHTML='<b>🏆 Mission Complete!</b><p>Your city reached 5,000 citizens and includes essential services. Pack 13 now saves this city so you can leave and return.</p>';localStorage.setItem('cityMissionComplete','yes');if(window.CWState){CWState.setProgress('citybuilder',100,{rating:score,budget});CWState.complete('citybuilder',{rating:score,budget});if(!completionRewarded){CWState.addXP(250,'Build Your City');CWState.addAchievement('city-planner','City Planner','🏙️');CWState.logActivity({id:'city-result',title:'Build Your City complete',icon:'🏙️',detail:`Rating ${score}/100 • +250 XP`,href:'city-builder.html'});completionRewarded=true;saveCity()}}playTone(true)}}
document.getElementById('undoCity').onclick=()=>{if(!history.length)return;const s=JSON.parse(history.pop());budget=s.budget;placements=s.placements;render();saveCity()};document.getElementById('resetCity').onclick=()=>{budget=2000000;placements=[];history=[];completionRewarded=false;localStorage.removeItem(SAVE_KEY);if(window.CWState)CWState.setProgress('citybuilder',0,{});render()};render();
