(()=>{
'use strict';
const STARTING_BUDGET=2350000;
const cityData={
 home:{icon:'🏠',name:'Homes',cost:180000,pop:1000,edu:0,health:0,safety:0,happy:2},
 school:{icon:'🏫',name:'School',cost:240000,pop:0,edu:28,health:0,safety:0,happy:4},
 hospital:{icon:'🏥',name:'Hospital',cost:320000,pop:0,edu:0,health:32,safety:3,happy:5},
 park:{icon:'🌳',name:'Park',cost:90000,pop:0,edu:0,health:4,safety:0,happy:18},
 fire:{icon:'🚒',name:'Fire Station',cost:210000,pop:0,edu:0,health:0,safety:30,happy:4},
 bus:{icon:'🚌',name:'Bus Hub',cost:160000,pop:0,edu:2,health:0,safety:2,happy:10},
 shop:{icon:'🛒',name:'Shops',cost:120000,pop:0,edu:0,health:0,safety:0,happy:8}
};
const SAVE_KEY='cw_city_builder_v3';let budget=STARTING_BUDGET,selected=null,placements=[],history=[],completionRewarded=false;
const board=document.getElementById('cityBoard');const tr=(en,fr)=>window.CWLang?.current?.()==='fr'?fr:en;
function loadCity(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');if(s&&Array.isArray(s.placements)){budget=Number.isFinite(+s.budget)?+s.budget:STARTING_BUDGET;placements=s.placements;completionRewarded=!!s.completionRewarded;cityInstruction.textContent=tr('Saved city restored. Keep building or reset to start again.','Ville enregistrée restaurée. Continue à construire ou réinitialise pour recommencer.')}}catch(_){} }
function saveCity(){localStorage.setItem(SAVE_KEY,JSON.stringify({budget,placements,completionRewarded,updatedAt:Date.now()}));if(window.CWState){const used=placements.filter(Boolean).length;CWState.setProgress('citybuilder',completionRewarded?100:Math.min(95,Math.round(used/12*100)),{budget,plots:used});if(!completionRewarded)CWState.setResume({id:'citybuilder',title:'Build Your City',icon:'🏙️',href:'city-builder.html',kind:'Build'})}}
loadCity();
for(let i=0;i<30;i++){const cell=document.createElement('button');cell.className='city-cell';cell.dataset.index=i;cell.setAttribute('aria-label','Empty city plot');cell.addEventListener('click',()=>place(selected,i));cell.addEventListener('dragover',e=>e.preventDefault());cell.addEventListener('drop',e=>{e.preventDefault();place(e.dataTransfer.getData('text/plain'),i)});board.appendChild(cell)}
document.querySelectorAll('.building-tool').forEach(b=>{b.onclick=()=>{selected=b.dataset.type;document.querySelectorAll('.building-tool').forEach(x=>x.classList.toggle('selected',x===b));cityInstruction.textContent=tr(`Selected ${cityData[selected].name}. Tap an empty plot.`,`Bâtiment sélectionné : ${cityData[selected].name}. Touche une parcelle vide.`)};b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',b.dataset.type))});
function place(type,index){if(!type)return;if(placements[index]){cityEvent.innerHTML=`<b>${tr('City Adviser','Conseiller de la ville')}</b><p>${tr('That plot is already occupied. Choose another one.','Cette parcelle est déjà occupée. Choisis-en une autre.')}</p>`;return}const d=cityData[type];if(budget<d.cost){cityEvent.innerHTML=`<b>${tr('Budget Alert','Alerte budget')}</b><p>${tr('You cannot afford that building. Re-think your plan or undo something.','Ton budget ne permet pas ce bâtiment. Revois ton plan ou annule une construction.')}</p>`;window.playTone?.(false);return}history.push(JSON.stringify({budget,placements}));budget-=d.cost;placements[index]=type;render();saveCity()}
function totals(){let t={pop:0,edu:0,health:0,safety:0,happy:0};placements.filter(Boolean).forEach(x=>{const d=cityData[x];t.pop+=d.pop;t.edu+=d.edu;t.health+=d.health;t.safety+=d.safety;t.happy+=d.happy});return t}
function render(){
 [...board.children].forEach((cell,i)=>{const type=placements[i];cell.innerHTML=type?`<span>${cityData[type].icon}</span><small>${cityData[type].name}</small>`:'<i>+</i>';cell.classList.toggle('filled',!!type)});
 const t=totals();document.getElementById('budget').textContent='£'+budget.toLocaleString('en-GB');population.textContent=t.pop.toLocaleString();education.textContent=Math.min(100,t.edu);health.textContent=Math.min(100,t.health);safetyScore.textContent=Math.min(100,t.safety);happiness.textContent=Math.min(100,t.happy);
 const has=k=>placements.includes(k);const checks={population:t.pop>=5000,school:has('school'),hospital:has('hospital'),park:has('park'),fire:has('fire'),bus:has('bus'),shop:has('shop'),education:t.edu>=50,reserve:budget>=30000&&budget<=70000};
 document.querySelectorAll('#objectiveList li').forEach(li=>{const ok=!!checks[li.dataset.key];li.classList.toggle('done',ok);li.textContent=(ok?'✅':'⬜')+' '+li.textContent.replace(/^[⬜✅]\s*/,'')});
 const essentials=Object.values(checks).filter(Boolean).length;let score=Math.round(essentials/Object.keys(checks).length*84);score+=Math.min(16,Math.round((Math.min(100,t.edu)+Math.min(100,t.health)+Math.min(100,t.safety)+Math.min(100,t.happy))/25));score=Math.min(100,score);rating.textContent=score;
 const win=Object.values(checks).every(Boolean);missionState.textContent=win?tr('MISSION COMPLETE','MISSION RÉUSSIE'):tr('IN PROGRESS','EN COURS');if(!win){let advice='';if(t.pop<5000)advice=tr('Your city still needs enough homes for 5,000 people.','Ta ville a encore besoin de logements pour 5 000 personnes.');else if(!has('school')||!has('hospital')||!has('park')||!has('fire')||!has('bus')||!has('shop'))advice=tr('Population is only one part of the mission. Check which essential service is still missing.','La population n’est qu’une partie de la mission. Vérifie quel service essentiel manque encore.');else if(t.edu<50)advice=tr('Your city has a school, but Education is still below 50. Strengthen education without destroying the budget plan.','Ta ville a une école, mais l’Éducation reste sous 50. Renforce-la sans casser ton budget.');else if(budget>70000)advice=tr(`Your services are working, but £${budget.toLocaleString('en-GB')} is still unallocated. The mission asks for a £30k–£70k emergency reserve.`,`Tes services fonctionnent, mais £${budget.toLocaleString('en-GB')} restent non affectées. La mission demande une réserve de 30k–70k £.`);else if(budget<30000)advice=tr('You spent too close to zero. A resilient city needs at least £30,000 left for emergencies. Undo and rebalance.','Tu as dépensé trop près de zéro. Une ville solide doit garder au moins 30 000 £ pour les urgences. Annule et rééquilibre.');if(advice)cityEvent.innerHTML=`<b>${tr('City Adviser','Conseiller de la ville')}</b><p>${advice}</p>`;}
 if(win){const firstWin=!completionRewarded;cityEvent.innerHTML=`<div class="city-complete-head"><b class="city-complete-title${firstWin?' flash-five':''}">🏆 ${tr('Mission Complete!','Mission réussie !')}</b><span class="city-retry-hint">↻ ${tr('Use Reset to try again','Utilise Réinitialiser pour recommencer')}</span></div><p>${tr(`Your balanced city serves at least 5,000 people, includes every essential service, has Education above 50 and keeps a £${budget.toLocaleString('en-GB')} emergency reserve.`,`Ta ville équilibrée accueille au moins 5 000 personnes, possède tous les services essentiels, dépasse 50 en Éducation et garde une réserve d’urgence de £${budget.toLocaleString('en-GB')}.`)}</p>`;localStorage.setItem('cityMissionComplete','yes');if(window.CWState){CWState.setProgress('citybuilder',100,{rating:score,budget});CWState.complete('citybuilder',{rating:score,budget});if(!completionRewarded){CWState.addXP(250,'Build Your City');CWState.addAchievement('city-planner','City Planner','🏙️');CWState.logActivity({id:'city-result',title:'Build Your City complete',icon:'🏙️',detail:`Rating ${score}/100 • £${budget.toLocaleString('en-GB')} left • +250 XP`,href:'city-builder.html'});completionRewarded=true;saveCity();window.playTone?.(true)}}}
}
undoCity.onclick=()=>{if(!history.length)return;const s=JSON.parse(history.pop());budget=s.budget;placements=s.placements;render();saveCity()};
resetCity.onclick=()=>{budget=STARTING_BUDGET;placements=[];history=[];completionRewarded=false;localStorage.removeItem(SAVE_KEY);if(window.CWState)CWState.setProgress('citybuilder',0,{});render()};render();
})();
