(()=>{
'use strict';
const currentLang=()=>window.CWLang?.current?.()||'en';
const t=(en,fr)=>currentLang()==='fr'?fr:en;
const missions={
 vehicle:{title:['Future Vehicle','Véhicule du futur'],prompt:['Design transport for 2050. Explain its energy source, passengers, safety system and the problem it solves.','Conçois un transport pour 2050. Explique son énergie, ses passagers, son système de sécurité et le problème qu’il résout.'],prompts:[['Who is it for?','Pour qui est-il ?'],['What powers it?','Quelle énergie l’alimente ?'],['What problem does it solve?','Quel problème résout-il ?'],['How is it kept safe?','Comment reste-t-il sûr ?']],choices:[['Electric','Électrique'],['Solar','Solaire'],['Hydrogen','Hydrogène'],['Shared transport','Transport partagé'],['Accessible design','Design accessible']]},
 room:{title:['Dream Room','Chambre de rêve'],prompt:['Plan a room with a £1,500 budget, useful storage, lighting and a clear purpose.','Planifie une pièce avec un budget de 1 500 £, du rangement utile, de l’éclairage et une fonction claire.'],prompts:[['Main purpose','Fonction principale'],['Who uses it?','Qui l’utilise ?'],['Biggest cost','Plus grosse dépense'],['One clever feature','Une idée astucieuse']],choices:[['Study zone','Zone d’étude'],['Storage','Rangement'],['Natural light','Lumière naturelle'],['Quiet space','Espace calme'],['Budget reserve','Réserve budget']]},
 park:{title:['Design a Park','Concevoir un parc'],prompt:['Balance play, nature, safety, accessibility and different community needs.','Équilibre jeu, nature, sécurité, accessibilité et besoins variés de la communauté.'],prompts:[['Who will use it?','Qui l’utilisera ?'],['Main activity','Activité principale'],['Safety idea','Idée sécurité'],['Accessibility idea','Idée accessibilité']],choices:[['Play area','Aire de jeux'],['Trees & nature','Arbres et nature'],['Sports','Sport'],['Quiet zone','Zone calme'],['Accessible paths','Chemins accessibles']]},
 robot:{title:['Invent a Robot','Inventer un robot'],prompt:['Give your robot one useful job. Decide what it senses, how it acts and what it must never be allowed to do.','Donne à ton robot un rôle utile. Décide ce qu’il détecte, comment il agit et ce qu’il ne doit jamais pouvoir faire.'],prompts:[['Robot job','Rôle du robot'],['What can it sense?','Que peut-il détecter ?'],['Who controls it?','Qui le contrôle ?'],['Safety rule','Règle de sécurité']],choices:[['Camera','Caméra'],['Distance sensor','Capteur de distance'],['Voice control','Commande vocale'],['Emergency stop','Arrêt d’urgence'],['Human approval','Validation humaine']]},
 story:{title:['Story Builder','Créateur d’histoires'],prompt:['Create a character, goal, problem, difficult choice, turning point and ending.','Crée un personnage, un objectif, un problème, un choix difficile, un tournant et une fin.'],prompts:[['Main character','Personnage principal'],['Goal','Objectif'],['Big problem','Grand problème'],['Difficult choice','Choix difficile']],choices:[['Friendship','Amitié'],['Adventure','Aventure'],['Mystery','Mystère'],['Technology','Technologie'],['Real-life lesson','Leçon de vie']]},
 mars:{title:['Mars Base','Base martienne'],prompt:['Plan a base that keeps people alive with air, water, food, power, shelter, communication and emergency systems.','Planifie une base qui garde les humains en vie grâce à l’air, l’eau, la nourriture, l’énergie, l’abri, la communication et les systèmes d’urgence.'],prompts:[['Power source','Source d’énergie'],['Water plan','Plan pour l’eau'],['Food plan','Plan nourriture'],['Emergency backup','Secours d’urgence']],choices:[['Solar power','Énergie solaire'],['Water recycling','Recyclage de l’eau'],['Greenhouse','Serre'],['Radiation shelter','Abri anti-radiations'],['Backup oxygen','Oxygène de secours']]}
};
const KEY='cw_creator_projects_v2';let active=null,selectedChoices=new Set();
const $=id=>document.getElementById(id);
function loadAll(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return {}}}
function saveAll(v){localStorage.setItem(KEY,JSON.stringify(v))}
function openMission(id){
 const m=missions[id];if(!m)return;active=id;selectedChoices=new Set();$('creatorTitle').textContent=m.title[currentLang()==='fr'?1:0];$('creatorPrompt').textContent=m.prompt[currentLang()==='fr'?1:0];
 $('creatorSteps').innerHTML=[t('Understand the brief','Comprendre le brief'),t('Make a plan','Faire un plan'),t('Choose design features','Choisir des éléments de conception'),t('Explain and improve your idea','Expliquer et améliorer ton idée')].map((x,i)=>`<li><span>${i+1}</span>${x}</li>`).join('');
 const saved=loadAll()[id]||{};$('creatorPlanFields').innerHTML=m.prompts.map((pair,i)=>`<label>${pair[currentLang()==='fr'?1:0]}<input data-plan="${i}" value="${(saved.plan?.[i]||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}" placeholder="${t('Type your answer','Écris ta réponse')}"></label>`).join('');
 selectedChoices=new Set(saved.choices||[]);$('creatorChoices').innerHTML=m.choices.map((pair,i)=>`<button type="button" class="creator-choice ${selectedChoices.has(i)?'selected':''}" data-choice="${i}">${pair[currentLang()==='fr'?1:0]}</button>`).join('');
 $('creatorChoices').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const i=+b.dataset.choice;if(selectedChoices.has(i))selectedChoices.delete(i);else selectedChoices.add(i);b.classList.toggle('selected',selectedChoices.has(i))});
 $('creatorNotes').value=saved.notes||'';$('creatorSaved').textContent=saved.updatedAt?t('Saved draft restored. Continue where you left off.','Brouillon restauré. Continue là où tu t’étais arrêté.'):'';
 $('creatorWorkspace').hidden=false;$('creatorWorkspace').scrollIntoView({behavior:'smooth',block:'start'});
}
function save(){if(!active)return;const all=loadAll();const plan=[...document.querySelectorAll('#creatorPlanFields [data-plan]')].map(i=>i.value.trim());all[active]={plan,choices:[...selectedChoices],notes:$('creatorNotes').value.trim(),updatedAt:Date.now()};saveAll(all);$('creatorSaved').textContent=t('✅ Project saved. You can leave and continue this mission later.','✅ Projet enregistré. Tu peux partir et reprendre cette mission plus tard.');if(window.CWState){CWState.setProgress('creator',Math.min(95,(Object.keys(all).length*16)),{lastMission:active});CWState.logActivity({id:'creator-'+active,title:`Creator Studio: ${missions[active].title[0]}`,icon:'🎨',detail:'Saved creative project',href:'creator.html'})}}
function clearDraft(){if(!active)return;const all=loadAll();delete all[active];saveAll(all);openMission(active);$('creatorSaved').textContent=t('Draft cleared. Start a new version.','Brouillon effacé. Commence une nouvelle version.')}
document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>openMission(b.dataset.mission));$('saveIdea').onclick=save;$('clearIdea').onclick=clearDraft;$('closeCreatorWorkspace').onclick=()=>{$('creatorWorkspace').hidden=true;document.querySelector('.creator-grid').scrollIntoView({behavior:'smooth',block:'start'})};
})();
