(()=>{
'use strict';
const lang=()=>window.CWLang?.current?.()||'en';
const t=(en,fr)=>lang()==='fr'?fr:en;
const missions={
 vehicle:{title:['Future Vehicle','Véhicule du futur'],prompt:['Sketch transport for 2050. Trace the guide or redesign it, add useful systems, then test your idea.','Dessine un transport pour 2050. Suis le guide ou transforme-le, ajoute des systèmes utiles puis teste ton idée.'],prompts:[['Who is it for?','Pour qui est-il ?'],['What powers it?','Quelle énergie l’alimente ?']],choices:[['Electric','Électrique'],['Solar','Solaire'],['Hydrogen','Hydrogène'],['Accessible design','Design accessible']],parts:[['🛞','Wheel'],['🔋','Battery'],['☀️','Solar'],['🪽','Wing'],['🪑','Seat']],coach:['How will your vehicle move safely around people?','Comment ton véhicule se déplacera-t-il en sécurité près des personnes ?'],test:'Your vehicle is moving. Check whether its power, safety and passenger design all make sense.'},
 room:{title:['Dream Room','Chambre de rêve'],prompt:['Draw the room layout, add furniture and lighting, colour it, then test whether the room works for its purpose.','Dessine la pièce, ajoute meubles et éclairage, colorie-la puis teste si elle correspond à sa fonction.'],prompts:[['Main purpose','Fonction principale'],['Who uses it?','Qui l’utilise ?']],choices:[['Study zone','Zone d’étude'],['Storage','Rangement'],['Natural light','Lumière naturelle'],['Quiet space','Espace calme']],parts:[['🛏️','Bed'],['🪑','Chair'],['🪟','Window'],['💡','Light'],['📚','Books']],coach:['Can someone move around your room comfortably without bumping into things?','Peut-on circuler facilement dans ta pièce sans se cogner ?'],test:'Room test running: look at movement space, lighting, storage and purpose.'},
 park:{title:['Design a Park','Concevoir un parc'],prompt:['Draw paths and zones, add nature and facilities, then test safety, accessibility and fun.','Dessine des chemins et des zones, ajoute nature et équipements puis teste sécurité, accessibilité et plaisir.'],prompts:[['Who will use it?','Qui l’utilisera ?'],['Main activity','Activité principale']],choices:[['Play area','Aire de jeux'],['Trees & nature','Arbres et nature'],['Sports','Sport'],['Accessible paths','Chemins accessibles']],parts:[['🌳','Tree'],['🛝','Play'],['🪑','Bench'],['🚰','Water'],['♿','Access']],coach:['Can a wheelchair user reach the important parts of your park?','Une personne en fauteuil roulant peut-elle atteindre les zones importantes du parc ?'],test:'Visitor simulation started: check paths, shade, seating, play and accessibility.'},
 robot:{title:['Invent a Robot','Inventer un robot'],prompt:['Trace or free-draw your robot, colour it, add sensors and tools, then test what it can do.','Suis le modèle ou dessine librement ton robot, colorie-le, ajoute capteurs et outils puis teste-le.'],prompts:[['Robot job','Rôle du robot'],['Safety rule','Règle de sécurité']],choices:[['Camera','Caméra'],['Distance sensor','Capteur de distance'],['Voice control','Commande vocale'],['Emergency stop','Arrêt d’urgence']],parts:[['👁️','Sensor'],['🦾','Arm'],['🛞','Wheel'],['📷','Camera'],['🛑','Stop']],coach:['How will your robot know that a person or wall is in front of it?','Comment ton robot saura-t-il qu’une personne ou un mur se trouve devant lui ?'],test:'Robot test started: movement, sensing and safety systems are being checked.'},
 story:{title:['Story Builder','Créateur d’histoires'],prompt:['Draw characters and scenes inside comic panels, move props around and build a visual story.','Dessine personnages et scènes dans des cases, déplace les éléments et construis une histoire visuelle.'],prompts:[['Main character','Personnage principal'],['Big problem','Grand problème']],choices:[['Friendship','Amitié'],['Adventure','Aventure'],['Mystery','Mystère'],['Technology','Technologie']],parts:[['🙂','Character'],['😮','Reaction'],['💬','Speech'],['🏠','Place'],['⭐','Event']],coach:['What changes between the first panel and the last panel?','Qu’est-ce qui change entre la première et la dernière case ?'],test:'Story preview started: check whether the pictures show a clear beginning, problem and change.'},
 mars:{title:['Mars Base','Base martienne'],prompt:['Sketch a Mars base, add survival systems, connect your ideas and test whether a crew could live there.','Dessine une base martienne, ajoute les systèmes de survie, relie tes idées et teste si un équipage pourrait y vivre.'],prompts:[['Power source','Source d’énergie'],['Emergency backup','Secours d’urgence']],choices:[['Solar power','Énergie solaire'],['Water recycling','Recyclage de l’eau'],['Greenhouse','Serre'],['Backup oxygen','Oxygène de secours']],parts:[['☀️','Power'],['💧','Water'],['🌱','Food'],['🫧','Oxygen'],['📡','Comms']],coach:['If one system fails, what keeps the crew alive until it is repaired?','Si un système tombe en panne, qu’est-ce qui garde l’équipage en vie jusqu’à la réparation ?'],test:'Mars-base systems test started: power, water, food, oxygen and emergency backup are being checked.'}
};
const KEY='cw_creator_projects_v3';
const $=id=>document.getElementById(id);
let active=null,selectedChoices=new Set(),tool='pen',colour='#5de4ff',templateOn=true,selectedObject=null,drawStrokes=0;
let undoStack=[],redoStack=[];
const canvas=$('creatorCanvas'),ctx=canvas.getContext('2d'),template=$('creatorTemplate'),tctx=template.getContext('2d'),stage=$('creatorDesignStage'),objectLayer=$('creatorObjects');
const colours=['#5de4ff','#ff77b7','#ffd45b','#5ee3a4','#ffffff','#ff647c','#9b6dff','#ff9d5d','#17243a'];
function loadAll(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return {}}}
function saveAll(v){localStorage.setItem(KEY,JSON.stringify(v))}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}
function setTool(name){tool=name;$('toolPen').classList.toggle('active',name==='pen');$('toolEraser').classList.toggle('active',name==='eraser');canvas.style.cursor=name==='eraser'?'cell':'crosshair'}
function historyPush(){try{undoStack.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(undoStack.length>18)undoStack.shift();redoStack=[]}catch(_){}}
function restoreImageData(data){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.putImageData(data,0,0)}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
let drawing=false,last=null;
canvas.addEventListener('pointerdown',e=>{if(!active)return;drawing=true;canvas.setPointerCapture(e.pointerId);historyPush();last=point(e);drawStrokes++});
canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=+$('brushSize').value;ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=colour;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p});
function endDraw(){drawing=false;ctx.globalCompositeOperation='source-over'}canvas.addEventListener('pointerup',endDraw);canvas.addEventListener('pointercancel',endDraw);
function drawTemplate(id){tctx.clearRect(0,0,template.width,template.height);if(!templateOn)return;tctx.save();tctx.strokeStyle='rgba(137,224,255,.38)';tctx.fillStyle='rgba(137,224,255,.06)';tctx.lineWidth=6;tctx.setLineDash([13,10]);
 const box=(x,y,w,h,r=22)=>{tctx.beginPath();if(tctx.roundRect)tctx.roundRect(x,y,w,h,r);else tctx.rect(x,y,w,h);tctx.fill();tctx.stroke()};
 const circle=(x,y,r)=>{tctx.beginPath();tctx.arc(x,y,r,0,Math.PI*2);tctx.fill();tctx.stroke()};
 if(id==='robot'){box(315,90,170,105,24);box(270,205,260,145,26);circle(365,140,11);circle(435,140,11);tctx.beginPath();tctx.moveTo(270,235);tctx.lineTo(205,285);tctx.moveTo(530,235);tctx.lineTo(595,285);tctx.moveTo(335,350);tctx.lineTo(320,420);tctx.moveTo(465,350);tctx.lineTo(480,420);tctx.stroke()}
 if(id==='vehicle'){box(170,190,455,120,42);tctx.beginPath();tctx.moveTo(260,190);tctx.lineTo(340,115);tctx.lineTo(500,115);tctx.lineTo(570,190);tctx.stroke();circle(275,325,45);circle(525,325,45)}
 if(id==='room'){box(110,70,580,320,8);box(160,235,210,105,12);box(470,210,140,95,12);box(470,105,120,75,8);tctx.beginPath();tctx.moveTo(400,70);tctx.lineTo(400,390);tctx.stroke()}
 if(id==='park'){tctx.beginPath();tctx.moveTo(90,345);tctx.bezierCurveTo(250,220,380,380,710,135);tctx.stroke();circle(180,145,55);circle(620,300,65);box(325,95,160,105,24)}
 if(id==='story'){box(45,55,220,335,12);box(290,55,220,335,12);box(535,55,220,335,12);circle(155,165,40);circle(400,165,40);circle(645,165,40)}
 if(id==='mars'){circle(250,250,115);circle(535,240,95);box(330,235,120,55,16);tctx.beginPath();tctx.moveTo(165,355);tctx.lineTo(635,355);tctx.moveTo(250,135);tctx.lineTo(250,70);tctx.moveTo(535,145);tctx.lineTo(600,80);tctx.stroke()}
 tctx.restore()}
function renderColours(){const box=$('creatorColors');box.innerHTML=colours.map((c,i)=>`<button type="button" class="creator-color${c===colour?' active':''}" data-colour="${c}" style="background:${c}" aria-label="Colour ${i+1}"></button>`).join('');box.querySelectorAll('[data-colour]').forEach(b=>b.onclick=()=>{colour=b.dataset.colour;box.querySelectorAll('.creator-color').forEach(x=>x.classList.toggle('active',x===b));setTool('pen')})}
function renderParts(m){$('creatorComponents').innerHTML='<b>'+t('Add movable parts:','Ajouter des éléments déplaçables :')+'</b>'+m.parts.map((p,i)=>`<button type="button" class="creator-component" data-part="${i}">${p[0]}<small>${p[1]}</small></button>`).join('');$('creatorComponents').querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>addObject(m.parts[+b.dataset.part][0]))}
function addObject(emoji,x=.5,y=.5,size=56){const o=document.createElement('div');o.className='creator-object';o.textContent=emoji;o.dataset.x=x;o.dataset.y=y;o.dataset.size=size;o.style.left=(x*100)+'%';o.style.top=(y*100)+'%';o.style.width=size+'px';o.style.height=size+'px';o.style.fontSize=(size*.56)+'px';objectLayer.appendChild(o);bindObject(o);selectObject(o)}
function bindObject(o){let dragging=false;const move=e=>{if(!dragging)return;const r=stage.getBoundingClientRect();let x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));o.dataset.x=x;o.dataset.y=y;o.style.left=(x*100)+'%';o.style.top=(y*100)+'%'};o.addEventListener('pointerdown',e=>{e.stopPropagation();dragging=true;o.setPointerCapture(e.pointerId);o.classList.add('dragging');selectObject(o)});o.addEventListener('pointermove',move);o.addEventListener('pointerup',()=>{dragging=false;o.classList.remove('dragging')});o.addEventListener('pointercancel',()=>{dragging=false;o.classList.remove('dragging')});o.addEventListener('click',e=>{e.stopPropagation();selectObject(o)})}
function selectObject(o){selectedObject=o;objectLayer.querySelectorAll('.creator-object').forEach(x=>x.classList.toggle('selected',x===o))}
stage.addEventListener('click',e=>{if(e.target===canvas||e.target===template||e.target===stage)selectObject(null)});
function objectData(){return [...objectLayer.children].map(o=>({emoji:o.textContent,x:+o.dataset.x,y:+o.dataset.y,size:+o.dataset.size}))}
function restoreObjects(list){objectLayer.innerHTML='';(list||[]).forEach(o=>addObject(o.emoji,o.x,o.y,o.size));selectObject(null)}
function restoreDrawing(data){ctx.clearRect(0,0,canvas.width,canvas.height);if(!data)return;const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,canvas.width,canvas.height);img.src=data}
function openMission(id){const m=missions[id];if(!m)return;active=id;selectedChoices=new Set();undoStack=[];redoStack=[];drawStrokes=0;selectedObject=null;$('creatorTitle').textContent=m.title[lang()==='fr'?1:0];$('creatorPrompt').textContent=m.prompt[lang()==='fr'?1:0];$('creatorSteps').innerHTML=[t('Start with the faint blueprint or switch it off','Commence avec le modèle pâle ou désactive-le'),t('Draw, colour and add movable parts','Dessine, colorie et ajoute des éléments déplaçables'),t('Test the creation and read the Design Coach','Teste la création et lis le conseil du coach'),t('Improve it, then save your project','Améliore-la puis enregistre ton projet')].map((x,i)=>`<li><span>${i+1}</span>${x}</li>`).join('');
 const saved=loadAll()[id]||{};drawStrokes=saved.drawing?3:0;templateOn=saved.templateOn!==false;$('toggleTemplate').textContent=templateOn?t('👻 Blueprint on','👻 Modèle activé'):t('👻 Blueprint off','👻 Modèle désactivé');drawTemplate(id);restoreDrawing(saved.drawing);restoreObjects(saved.objects);renderParts(m);renderColours();$('creatorCoach').textContent=m.coach[lang()==='fr'?1:0];$('creatorTestResult').textContent='';$('creatorPlanFields').innerHTML=m.prompts.map((pair,i)=>`<label>${pair[lang()==='fr'?1:0]}<input data-plan="${i}" value="${esc(saved.plan?.[i])}" placeholder="${t('Optional answer','Réponse facultative')}"></label>`).join('');selectedChoices=new Set(saved.choices||[]);$('creatorChoices').innerHTML=m.choices.map((pair,i)=>`<button type="button" class="creator-choice ${selectedChoices.has(i)?'selected':''}" data-choice="${i}">${pair[lang()==='fr'?1:0]}</button>`).join('');$('creatorChoices').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const i=+b.dataset.choice;selectedChoices.has(i)?selectedChoices.delete(i):selectedChoices.add(i);b.classList.toggle('selected',selectedChoices.has(i))});$('creatorNotes').value=saved.notes||'';$('creatorSaved').textContent=saved.updatedAt?t('Saved project restored. Keep creating.','Projet enregistré restauré. Continue à créer.'):'';$('creatorWorkspace').hidden=false;$('creatorWorkspace').scrollIntoView({behavior:'smooth',block:'start'})}
function save(){if(!active)return;const all=loadAll();const plan=[...document.querySelectorAll('#creatorPlanFields [data-plan]')].map(i=>i.value.trim());all[active]={plan,choices:[...selectedChoices],notes:$('creatorNotes').value.trim(),drawing:canvas.toDataURL('image/png'),objects:objectData(),templateOn,updatedAt:Date.now()};try{saveAll(all);$('creatorSaved').textContent=t('✅ Project saved. You can return and continue later.','✅ Projet enregistré. Tu peux revenir et continuer plus tard.')}catch(_){$('creatorSaved').textContent=t('This drawing is too large to save on this prototype device. Clear some detail and try again.','Ce dessin est trop volumineux pour être enregistré sur cet appareil prototype.')}if(window.CWState){CWState.setProgress('creator',Math.min(95,Object.keys(all).length*16),{lastMission:active});CWState.logActivity({id:'creator-'+active,title:`Creator Studio: ${missions[active].title[0]}`,icon:'🎨',detail:'Saved interactive design',href:'creator.html'})}}
function clearProject(){if(!active)return;ctx.clearRect(0,0,canvas.width,canvas.height);objectLayer.innerHTML='';undoStack=[];redoStack=[];drawStrokes=0;selectedObject=null;const all=loadAll();delete all[active];saveAll(all);$('creatorNotes').value='';document.querySelectorAll('#creatorPlanFields input').forEach(i=>i.value='');$('creatorSaved').textContent=t('Project cleared. Start a new design.','Projet effacé. Commence un nouveau design.');$('creatorTestResult').textContent=''}
function testCreation(){if(!active)return;const objectCount=objectLayer.children.length;const enough=drawStrokes>=3||objectCount>=3;if(!enough){$('creatorTestResult').textContent=t('Add more of your own drawing or at least three movable parts before testing.','Ajoute davantage de dessin ou au moins trois éléments déplaçables avant de tester.');$('creatorCoach').textContent=t('Your design needs more detail before the test can tell you anything useful.','Ton design a besoin de plus de détails avant qu’un test soit utile.');return}stage.classList.remove('testing');void stage.offsetWidth;stage.classList.add('testing');$('creatorTestResult').textContent=t('Testing your creation…','Test de ta création…');setTimeout(()=>{$('creatorTestResult').textContent=t('✅ '+missions[active].test,'✅ Test terminé. Lis le conseil du coach et améliore ton design.');$('creatorCoach').textContent=missions[active].coach[lang()==='fr'?1:0];window.playTone?.(true)},900)}
document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>openMission(b.dataset.mission));
$('toolPen').onclick=()=>setTool('pen');$('toolEraser').onclick=()=>setTool('eraser');$('toggleTemplate').onclick=()=>{templateOn=!templateOn;$('toggleTemplate').textContent=templateOn?t('👻 Blueprint on','👻 Modèle activé'):t('👻 Blueprint off','👻 Modèle désactivé');drawTemplate(active)};$('undoDraw').onclick=()=>{if(!undoStack.length)return;redoStack.push(ctx.getImageData(0,0,canvas.width,canvas.height));restoreImageData(undoStack.pop())};$('redoDraw').onclick=()=>{if(!redoStack.length)return;undoStack.push(ctx.getImageData(0,0,canvas.width,canvas.height));restoreImageData(redoStack.pop())};$('deleteObject').onclick=()=>{if(selectedObject){selectedObject.remove();selectedObject=null}};$('testCreation').onclick=testCreation;$('saveIdea').onclick=save;$('clearIdea').onclick=clearProject;$('closeCreatorWorkspace').onclick=()=>{$('creatorWorkspace').hidden=true;document.querySelector('.creator-grid').scrollIntoView({behavior:'smooth',block:'start'})};renderColours();
})();
