const intro=document.getElementById('gameIntro'),arena=document.getElementById('gameArena'),results=document.getElementById('gameResults');let mode='mixed',round=0,score=0,correct=0,xp=0,combo=0,lives=3,current=[],timerId,time=15,locked=false;
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode});
function getPool(){let pool=WORLD_QUESTIONS.filter(q=>mode==='mixed'||q.mode===mode||q.mode==='mixed'&&mode==='mixed');if(mode==='flags')pool=WORLD_QUESTIONS.filter(q=>q.mode==='flags');if(mode==='capitals')pool=WORLD_QUESTIONS.filter(q=>q.mode==='capitals');const key='flagquest_seen_'+mode;let seen=JSON.parse(localStorage.getItem(key)||'[]');let unseen=pool.filter(q=>!seen.includes(q.id));if(unseen.length<10){seen=[];unseen=[...pool]}unseen.sort(()=>Math.random()-.5);current=unseen.slice(0,10);localStorage.setItem(key,JSON.stringify([...seen,...current.map(q=>q.id)]));}
function start(){getPool();round=0;score=0;correct=0;xp=0;combo=0;lives=3;intro.hidden=true;results.hidden=true;arena.hidden=false;updateHud();showRound()}
function updateHud(){document.getElementById('gameXp').textContent=xp;document.getElementById('combo').textContent=combo;document.getElementById('lives').textContent=lives;document.getElementById('score').textContent=score}
function showRound(){if(round>=current.length||lives<=0){endGame();return}locked=false;const q=current[round];document.getElementById('roundLabel').textContent=`ROUND ${round+1} / ${current.length}`;document.getElementById('questionIcon').textContent=q.icon;document.getElementById('questionCategory').textContent=q.category;document.getElementById('gameQuestion').textContent=q.q;document.getElementById('gameFeedback').textContent='';const choices=[...q.choices].sort(()=>Math.random()-.5);const grid=document.getElementById('answerGrid');grid.innerHTML=choices.map(c=>`<button data-a="${c}">${c}</button>`).join('');grid.querySelectorAll('button').forEach(b=>b.onclick=()=>answer(b,q));time=15;document.getElementById('timerBar').style.width='100%';clearInterval(timerId);timerId=setInterval(()=>{time--;document.getElementById('timerBar').style.width=(time/15*100)+'%';if(time<=0){clearInterval(timerId);timeout(q)}},1000)}
function timeout(q){if(locked)return;locked=true;lives--;combo=0;document.getElementById('gameFeedback').innerHTML=`⏱️ Time! Correct answer: <b>${q.a}</b>`;playTone(false);updateHud();setTimeout(()=>{round++;showRound()},900)}
function answer(btn,q){if(locked)return;locked=true;clearInterval(timerId);const ok=btn.dataset.a===q.a;document.querySelectorAll('#answerGrid button').forEach(b=>{if(b.dataset.a===q.a)b.classList.add('correct')});if(ok){btn.classList.add('correct');correct++;combo++;const bonus=100+combo*15+time*2;score+=bonus;xp+=20+combo*2;document.getElementById('gameFeedback').textContent=`✅ Correct! +${bonus}`;playTone(true)}else{btn.classList.add('wrong');lives--;combo=0;document.getElementById('gameFeedback').innerHTML=`❌ Correct answer: <b>${q.a}</b>`;playTone(false)}updateHud();setTimeout(()=>{round++;showRound()},850)}
function endGame(){clearInterval(timerId);arena.hidden=true;results.hidden=false;document.getElementById('finalScore').textContent=score;document.getElementById('finalCorrect').textContent=correct;document.getElementById('finalXp').textContent=xp;document.getElementById('resultCopy').textContent=correct>=8?'Excellent world knowledge. Your next set will avoid the questions you just used.':correct>=5?'Solid run. A new shuffled set is ready when you are.':'Good start. Review the world clues and try another fresh set.';localStorage.setItem('lastFlagQuest',JSON.stringify({score,correct,xp,date:Date.now()}));}
document.getElementById('startGame').onclick=start;document.getElementById('playAgain').onclick=start;
