const facts=['Octopuses have three hearts.','A day on Venus is longer than a year on Venus.','The Pacific Ocean is larger than all Earth’s land area combined.','Your skin is your body’s largest organ.','Some bamboo can grow extremely quickly under the right conditions.','The word “robot” came from a Czech word connected with forced work.'];
let factIndex=0;const quickFact=document.getElementById('quickFact');document.getElementById('newFactBtn').onclick=()=>{factIndex=(factIndex+1+Math.floor(Math.random()*(facts.length-1)))%facts.length;quickFact.textContent=facts[factIndex]};
const modal=document.getElementById('activityModal'),content=document.getElementById('modalContent');
const templates={
 safety:`<span class="eyebrow">SAFETY MISSION</span><h2>Spot the scam</h2><p>You receive: <b>“You won a new phone! Sign in with your game password in the next 5 minutes.”</b></p><div class="modal-options"><button data-safe="no">Click quickly so the prize is not lost.</button><button data-safe="yes">Do not click. Check the source and tell a trusted adult if worried.</button><button data-safe="no">Reply with the password instead.</button></div><p id="safeFeedback"></p>`,
 why:`<span class="eyebrow">ASK WHY?</span><h2>Why do volcanoes erupt?</h2><p>Earth's outer layer is broken into moving tectonic plates. In some places, movement allows molten rock called magma to rise. Pressure can build until magma, gases and other material escape through the crust.</p><p><b>Knowledge path:</b> Volcanoes → Plate tectonics → Earthquakes → Earth's layers.</p>`,
 create:`<span class="eyebrow">CREATIVE WORLD</span><h2>Design a city for 100,000 people.</h2><p>Where will you place housing, schools, hospitals, parks, transport, shops and emergency services? A future build will make this a drag-and-drop planning game.</p>`,
 mind:`<span class="eyebrow">ME, BODY & MIND</span><h2>Reset challenge</h2><p>You are frustrated because a task went wrong three times. Pick a healthy next move: take a short break, identify one thing to change, then try again or ask for help.</p>`,
 uk:`<span class="eyebrow">MY UK</span><h2>How does a law begin?</h2><p>This future interactive path will introduce Parliament, bills, debates, votes and Royal Assent in neutral, age-appropriate language, with differences across UK legal systems explained where relevant.</p>`,
 future:`<span class="eyebrow">MY FUTURE</span><h2>Run a tiny business</h2><p>Choose a product, estimate costs, set a price and see whether your pretend business makes a profit. This will connect money maths to real-life decision making.</p>`
};
function openModal(html){content.innerHTML=html;modal.classList.add('open');modal.setAttribute('aria-hidden','false');content.querySelectorAll('[data-safe]').forEach(b=>b.onclick=()=>{const ok=b.dataset.safe==='yes';document.getElementById('safeFeedback').innerHTML=ok?'✅ <b>Good choice.</b> Urgency + prize + password request are warning signs.':'⚠️ <b>Try again.</b> Never give a password because a message pressures you.';playTone(ok)})}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{if(b.dataset.open==='quiz')startMiniQuiz();else openModal(templates[b.dataset.open])});
modal.querySelector('.modal-close').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
function startMiniQuiz(){const bank=[...WORLD_QUESTIONS].sort(()=>Math.random()-.5).slice(0,5);let i=0,score=0;const render=()=>{if(i>=bank.length){openModal(`<span class="eyebrow">MINI QUIZ COMPLETE</span><h2>${score}/5 correct</h2><p>${score>=4?'Excellent — your knowledge bank is growing.':'Good start. The full platform will explain every answer and serve a fresh set next time.'}</p>`);return}const q=bank[i];openModal(`<span class="eyebrow">QUICK KNOWLEDGE CHECK • ${i+1}/5</span><h2>${q.q}</h2><div class="modal-options">${q.choices.sort(()=>Math.random()-.5).map(x=>`<button data-answer="${x.replaceAll('"','&quot;')}">${x}</button>`).join('')}</div><p id="quizFeed"></p>`);content.querySelectorAll('[data-answer]').forEach(btn=>btn.onclick=()=>{const ok=btn.dataset.answer===q.a;document.getElementById('quizFeed').innerHTML=ok?'✅ Correct!':'❌ Not this time. Correct answer: <b>'+q.a+'</b>';playTone(ok);if(ok)score++;setTimeout(()=>{i++;render()},650)})};render()}
document.getElementById('surpriseBtn').onclick=()=>{const pool=[templates.why,templates.create,templates.future,templates.uk,templates.safety];openModal(pool[Math.floor(Math.random()*pool.length)])};
document.getElementById('saveLaterBtn').onclick=()=>{localStorage.setItem('savedJapan','yes');openModal('<span class="eyebrow">SAVED</span><h2>Japan mission saved.</h2><p>In the production platform this will sync to the child profile database so it follows them across approved devices.</p>')};
const searchMap={shark:'Animal Kingdom → Ocean World → Shark facts → Shark quiz',japan:'World Explorer → Japan → Tokyo → Culture → Japan Challenge',money:'Life Lab → Budgeting → Money World → Business Lab',space:'Discovery Universe → Space Station → Planets → Missions',scam:'People & Safety → Online Safety → Spot the Scam'};
function doSearch(){const v=document.getElementById('globalSearch').value.toLowerCase().trim();let r='Try: Japan, sharks, money, space or scam.';for(const k in searchMap)if(v.includes(k)){r=searchMap[k];break}openModal(`<span class="eyebrow">GLOBAL SEARCH • PROTOTYPE</span><h2>Discovery path</h2><div class="search-result">${r}</div><p>The production search will index thousands of connected topics and activities.</p>`)}document.getElementById('searchBtn').onclick=doSearch;document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});
