(()=>{
const fr=()=>window.CWLang?.current?.()==='fr', tr=(en,frText)=>fr()?frText:en;
const tabs=[...document.querySelectorAll('.country-nav button')],panels=[...document.querySelectorAll('.country-tab')];
function goTab(id){tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===id));panels.forEach(p=>p.classList.toggle('active',p.id===id));document.querySelector('.country-content').scrollIntoView({behavior:'smooth',block:'start'});const pct={snapshot:68,cities:74,culture:81,life:90,quiz:95}[id]||68;countryProgressBar.style.width=pct+'%';countryProgressText.textContent=tr('Mission progress: ','Progression de la mission : ')+pct+'%';localStorage.setItem('japanProgress',pct);if(window.CWState){CWState.setProgress('japan',pct,{tab:id});if(!CWState.load().completed.japan)CWState.setResume({id:'japan',title:'Japan World Mission',icon:'🇯🇵',href:'japan.html',kind:'Explore'})}}
tabs.forEach(b=>b.onclick=()=>goTab(b.dataset.tab));document.querySelectorAll('[data-country-next]').forEach(b=>b.onclick=()=>goTab(b.dataset.countryNext));
document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer==='correct';scenarioFeedback.textContent=ok?tr('✅ Correct. 22 + 8 + 10 = 40 minutes, so leaving at 09:20 gives the full buffer.','✅ Correct. 22 + 8 + 10 = 40 minutes : partir à 09 h 20 donne toute la marge prévue.'):tr('Not quite. Add the 22-minute train, 8-minute walk and 10-minute buffer: 40 minutes before 10:00.','Pas encore. Additionne 22 minutes de train, 8 minutes de marche et 10 minutes de marge : 40 minutes avant 10 h.');window.playTone?.(ok)});
let qi=0,score=0;const box=document.getElementById('japanQuiz');
function renderQuiz(){
 if(qi>=JAPAN_QUESTIONS.length){box.innerHTML=`<div class="trophy">🛂</div><h3>${tr('Passport mission complete!','Mission passeport terminée !')}</h3><p>${tr('You scored','Score')} <b>${score}/${JAPAN_QUESTIONS.length}</b>. ${score>=4?tr('Japan Explorer stamp unlocked.','Tampon Explorateur du Japon débloqué.'):tr('Review the mission and try a fresh set later.','Revois la mission et réessaie plus tard.')}</p><button class="btn small primary" id="stampBtn">${tr('Save progress + return to HQ','Enregistrer + retour au HQ')}</button>`;countryProgressBar.style.width='100%';countryProgressText.textContent=tr('Mission progress: 100%','Progression de la mission : 100%');stampBtn.onclick=()=>{localStorage.setItem('japanStamp','earned');localStorage.setItem('japanProgress','100');if(window.CWState){const s=CWState.load(),first=!s.passport.some(x=>x.code==='JP');CWState.setProgress('japan',100,{score});CWState.complete('japan',{score});CWState.addPassport('JP',{title:'Japan',flag:'🇯🇵'});if(first)CWState.addXP(180,'Japan World Mission');CWState.logActivity({id:'japan-result',title:'Japan Passport stamp earned',icon:'🇯🇵',detail:`Quiz ${score}/${JAPAN_QUESTIONS.length}${first?' • +180 XP':''}`,href:'japan.html'});CWState.addAchievement('japan-explorer','Japan Explorer','🛂')}showToast(tr('🛂 Japan stamp saved to your prototype profile','🛂 Tampon Japon enregistré dans ton profil'));setTimeout(()=>location.href='hq.html',1000)};return}
 const q=JAPAN_QUESTIONS[qi],en=q.choices,loc=fr()?(q.choicesFr||q.choices):q.choices,order=en.map((_,i)=>i).sort(()=>Math.random()-.5);box.innerHTML=`<span class="eyebrow">${tr('QUESTION','QUESTION')} ${qi+1}/${JAPAN_QUESTIONS.length}</span><h3>${fr()?(q.qFr||q.q):q.q}</h3>${order.map(i=>`<button data-qindex="${i}">${loc[i]}</button>`).join('')}<p id="jfeed"></p>`;box.querySelectorAll('[data-qindex]').forEach(b=>b.onclick=()=>{const i=+b.dataset.qindex,ok=en[i]===q.a;jfeed.textContent=ok?tr('✅ Correct!','✅ Correct !'):tr(`❌ Correct answer: ${fr()?(q.aFr||q.a):q.a}`,`❌ Bonne réponse : ${fr()?(q.aFr||q.a):q.a}`);window.playTone?.(ok);if(ok)score++;setTimeout(()=>{qi++;renderQuiz()},650)})
}
renderQuiz();function showToast(t){const toast=document.getElementById('toast');toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
})();
