(()=>{
'use strict';
const products=[
{id:'chicken',name:'Chicken thighs',icon:'🍗',price:6.5,cat:'main'},{id:'beans',name:'Mixed beans',icon:'🫘',price:2.2,cat:'main'},{id:'pasta',name:'Pasta',icon:'🍝',price:1.4,cat:'side'},{id:'rice',name:'Rice',icon:'🍚',price:1.8,cat:'side'},{id:'potato',name:'Potatoes',icon:'🥔',price:2.4,cat:'side'},{id:'tomato',name:'Tomatoes',icon:'🍅',price:1.9,cat:'veg'},{id:'broccoli',name:'Broccoli',icon:'🥦',price:1.6,cat:'veg'},{id:'carrot',name:'Carrots',icon:'🥕',price:1.1,cat:'veg'},{id:'apple',name:'Apples',icon:'🍎',price:2.2,cat:'veg'},{id:'salad',name:'Salad bag',icon:'🥗',price:1.8,cat:'veg'},{id:'bread',name:'Wholemeal bread',icon:'🍞',price:1.5,cat:'side'},{id:'cheese',name:'Cheddar cheese',icon:'🧀',price:3.25,cat:'extra'},{id:'yoghurt',name:'Yoghurt',icon:'🥣',price:2.1,cat:'extra'},{id:'juice',name:'Orange juice',icon:'🧃',price:2.4,cat:'extra'},{id:'fish',name:'White fish fillets',icon:'🐟',price:7.25,cat:'main'},{id:'eggs',name:'Eggs',icon:'🥚',price:2.75,cat:'main'},{id:'peas',name:'Frozen peas',icon:'🫛',price:1.5,cat:'veg'},{id:'sauce',name:'Tomato sauce',icon:'🥫',price:1.2,cat:'extra'}];
const quantities={};let activeFilter='all';const grid=document.getElementById('productGrid');const tr=(s)=>window.CWLang?.t?.(s)||s;
function total(){return products.reduce((sum,p)=>sum+(quantities[p.id]||0)*p.price,0)}
function count(){return Object.values(quantities).reduce((s,n)=>s+n,0)}
function label(cat){return cat==='main'?'Main meal':cat==='veg'?'Fruit / veg':cat==='side'?'Side':'Extra'}
function renderProducts(){grid.innerHTML=products.filter(p=>activeFilter==='all'||p.cat===activeFilter).map(p=>`<article class="product-card"><span class="product-icon">${p.icon}</span><b>${tr(p.name)}</b><small>${tr(label(p.cat))}</small><strong>£${p.price.toFixed(2)}</strong><div class="product-controls"><button type="button" class="qty-btn minus" data-minus="${p.id}" aria-label="Remove one ${p.name}" ${!quantities[p.id]?'disabled':''}>−</button><span class="qty-value">${quantities[p.id]||0}</span><button type="button" class="qty-btn plus" data-add="${p.id}" aria-label="Add one ${p.name}">+</button></div></article>`).join('');grid.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>change(b.dataset.add,1));grid.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(b.dataset.minus,-1))}
function change(id,delta){const p=products.find(x=>x.id===id);const next=Math.max(0,(quantities[id]||0)+delta);if(delta>0&&total()+p.price>35){feedback(tr('That would take you over £35. Try a different choice.'),false);return}quantities[id]=next;if(!next)delete quantities[id];renderProducts();renderCart();window.playTone?.(delta>0)}
function renderCart(){const c=document.getElementById('cartItems'),sum=total();const chosen=products.filter(p=>quantities[p.id]);c.innerHTML=chosen.length?chosen.map(p=>`<div class="cart-item"><span>${p.icon}</span><b>${tr(p.name)} × ${quantities[p.id]}</b><small>£${(p.price*quantities[p.id]).toFixed(2)}</small><button type="button" data-cart-minus="${p.id}" aria-label="Remove one">−</button></div>`).join(''):`<p class="empty">${tr('Nothing added yet.')}</p>`;c.querySelectorAll('[data-cart-minus]').forEach(b=>b.onclick=()=>change(b.dataset.cartMinus,-1));cartTotal.textContent='£'+sum.toFixed(2);budgetLeft.textContent='£'+(35-sum).toFixed(2);cartCount.textContent=count();const hasMain=products.some(p=>p.cat==='main'&&quantities[p.id]),hasVeg=products.some(p=>p.cat==='veg'&&quantities[p.id]);reqMain.textContent=(hasMain?'✓':'○')+' '+tr('Main meal item');reqVeg.textContent=(hasVeg?'✓':'○')+' '+tr('Fruit or vegetable');reqBudget.textContent='✓ '+tr('Stay within £35')}
function feedback(msg,ok){basketFeedback.innerHTML=(ok?'✅ ':'💡 ')+msg}
checkBasket.onclick=()=>{const sum=total(),hasMain=products.some(p=>p.cat==='main'&&quantities[p.id]),hasVeg=products.some(p=>p.cat==='veg'&&quantities[p.id]);if(!count())return feedback(tr('Add some food first.'),false);if(!hasMain)return feedback(tr('Your plan needs a main meal item.'),false);if(!hasVeg)return feedback(tr('Add at least one fruit or vegetable item.'),false);localStorage.setItem('lifeLab35',JSON.stringify({total:sum,quantities,updatedAt:Date.now()}));if(window.CWState){CWState.addXP(120,'£35 Life Lab');CWState.setProgress('lifelab',100,{total:sum,items:count()});CWState.complete('lifelab',{total:sum,items:count()});CWState.logActivity({id:'lifelab-result',title:'£35 Life Lab complete',icon:'💷',detail:`Basket £${sum.toFixed(2)} • £${(35-sum).toFixed(2)} spare • +120 XP`,href:'life-lab.html'});CWState.addAchievement('budget-planner','Budget Planner','💷')}feedback(tr(`Challenge complete! You planned a basket for £${sum.toFixed(2)} and kept £${(35-sum).toFixed(2)} spare.`),true);window.playTone?.(true)};
document.querySelectorAll('.shop-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.shop-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderProducts()});renderProducts();renderCart();
})();
