window.WORLD_QUESTIONS = [
{id:'w001',mode:'flags',icon:'🇯🇵',category:'FLAG',q:'Which country uses this flag?',a:'Japan',choices:['Japan','South Korea','China','Vietnam']},
{id:'w002',mode:'flags',icon:'🇳🇬',category:'FLAG',q:'Which country uses this flag?',a:'Nigeria',choices:['Ghana','Nigeria','Kenya','Cameroon']},
{id:'w003',mode:'flags',icon:'🇧🇷',category:'FLAG',q:'Which country uses this flag?',a:'Brazil',choices:['Brazil','Argentina','Portugal','Mexico']},
{id:'w004',mode:'flags',icon:'🇨🇦',category:'FLAG',q:'Which country uses this flag?',a:'Canada',choices:['Canada','United States','Denmark','Austria']},
{id:'w005',mode:'flags',icon:'🇮🇳',category:'FLAG',q:'Which country uses this flag?',a:'India',choices:['India','Ireland','Niger','Iran']},
{id:'w006',mode:'flags',icon:'🇰🇪',category:'FLAG',q:'Which country uses this flag?',a:'Kenya',choices:['Kenya','South Africa','Uganda','Malawi']},
{id:'w007',mode:'flags',icon:'🇦🇺',category:'FLAG',q:'Which country uses this flag?',a:'Australia',choices:['Australia','New Zealand','United Kingdom','Fiji']},
{id:'w008',mode:'flags',icon:'🇲🇽',category:'FLAG',q:'Which country uses this flag?',a:'Mexico',choices:['Mexico','Italy','Spain','Peru']},
{id:'w009',mode:'flags',icon:'🇿🇦',category:'FLAG',q:'Which country uses this flag?',a:'South Africa',choices:['South Africa','Zimbabwe','Namibia','Botswana']},
{id:'w010',mode:'flags',icon:'🇰🇷',category:'FLAG',q:'Which country uses this flag?',a:'South Korea',choices:['South Korea','Japan','Thailand','Mongolia']},
{id:'w011',mode:'flags',icon:'🇫🇷',category:'FLAG',q:'Which country uses this flag?',a:'France',choices:['France','Netherlands','Russia','Luxembourg']},
{id:'w012',mode:'flags',icon:'🇯🇲',category:'FLAG',q:'Which country uses this flag?',a:'Jamaica',choices:['Jamaica','Guyana','Tanzania','Bahamas']},
{id:'w013',mode:'flags',icon:'🇪🇬',category:'FLAG',q:'Which country uses this flag?',a:'Egypt',choices:['Egypt','Syria','Iraq','Yemen']},
{id:'w014',mode:'flags',icon:'🇦🇷',category:'FLAG',q:'Which country uses this flag?',a:'Argentina',choices:['Argentina','Uruguay','Greece','Guatemala']},
{id:'w015',mode:'flags',icon:'🇳🇴',category:'FLAG',q:'Which country uses this flag?',a:'Norway',choices:['Norway','Iceland','Denmark','Finland']},
{id:'w016',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Japan?',a:'Tokyo',choices:['Tokyo','Kyoto','Osaka','Nagoya']},
{id:'w017',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of France?',a:'Paris',choices:['Paris','Lyon','Marseille','Nice']},
{id:'w018',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Kenya?',a:'Nairobi',choices:['Nairobi','Mombasa','Kisumu','Kampala']},
{id:'w019',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Canada?',a:'Ottawa',choices:['Ottawa','Toronto','Vancouver','Montreal']},
{id:'w020',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Australia?',a:'Canberra',choices:['Canberra','Sydney','Melbourne','Perth']},
{id:'w021',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Brazil?',a:'Brasília',choices:['Brasília','Rio de Janeiro','São Paulo','Salvador']},
{id:'w022',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Nigeria?',a:'Abuja',choices:['Abuja','Lagos','Kano','Port Harcourt']},
{id:'w023',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Egypt?',a:'Cairo',choices:['Cairo','Alexandria','Giza','Luxor']},
{id:'w024',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Argentina?',a:'Buenos Aires',choices:['Buenos Aires','Córdoba','Rosario','Mendoza']},
{id:'w025',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of South Korea?',a:'Seoul',choices:['Seoul','Busan','Incheon','Daegu']},
{id:'w026',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of Mexico?',a:'Mexico City',choices:['Mexico City','Guadalajara','Monterrey','Cancún']},
{id:'w027',mode:'capitals',icon:'🏙️',category:'CAPITAL',q:'What is the capital of India?',a:'New Delhi',choices:['New Delhi','Mumbai','Bengaluru','Kolkata']},
{id:'w028',mode:'mixed',icon:'🌍',category:'WORLD',q:'Which continent is Brazil in?',a:'South America',choices:['South America','North America','Europe','Africa']},
{id:'w029',mode:'mixed',icon:'🗻',category:'WORLD',q:'Mount Fuji is in which country?',a:'Japan',choices:['Japan','China','Nepal','South Korea']},
{id:'w030',mode:'mixed',icon:'🌊',category:'WORLD',q:'Which is the largest ocean on Earth?',a:'Pacific Ocean',choices:['Pacific Ocean','Atlantic Ocean','Indian Ocean','Arctic Ocean']},
{id:'w031',mode:'mixed',icon:'🧭',category:'WORLD',q:'Which direction is opposite to east?',a:'West',choices:['West','North','South','North-east']},
{id:'w032',mode:'mixed',icon:'🏜️',category:'WORLD',q:'The Sahara Desert is mainly in which continent?',a:'Africa',choices:['Africa','Asia','South America','Europe']},
{id:'w033',mode:'mixed',icon:'🌎',category:'WORLD',q:'Which country is completely surrounded by South Africa?',a:'Lesotho',choices:['Lesotho','Namibia','Botswana','Eswatini']},
{id:'w034',mode:'mixed',icon:'💴',category:'WORLD',q:'Which currency is used in Japan?',a:'Yen',choices:['Yen','Won','Yuan','Baht']},
{id:'w035',mode:'mixed',icon:'🗣️',category:'WORLD',q:'Portuguese is the main official language of which South American country?',a:'Brazil',choices:['Brazil','Argentina','Chile','Peru']},
{id:'w036',mode:'mixed',icon:'🗺️',category:'WORLD',q:'Which country has the city of Nairobi?',a:'Kenya',choices:['Kenya','Nigeria','Ghana','Ethiopia']},
{id:'w037',mode:'mixed',icon:'🏝️',category:'WORLD',q:'Japan is best described geographically as what?',a:'An island country',choices:['An island country','A landlocked country','A single-city state','A desert country']},
{id:'w038',mode:'mixed',icon:'🚅',category:'WORLD',q:'The Shinkansen is most closely associated with which form of transport?',a:'High-speed rail',choices:['High-speed rail','Ferries','Aircraft','Buses']},
{id:'w039',mode:'mixed',icon:'🌐',category:'WORLD',q:'Which line divides Earth into Northern and Southern Hemispheres?',a:'The Equator',choices:['The Equator','The Prime Meridian','The Tropic of Cancer','The Arctic Circle']},
{id:'w040',mode:'mixed',icon:'⛰️',category:'WORLD',q:'Mount Everest lies in which mountain range?',a:'The Himalayas',choices:['The Himalayas','The Andes','The Alps','The Rockies']},
{id:'s001',mode:'mixed',icon:'🪐',category:'SCIENCE',q:'Which planet is the largest in our Solar System?',a:'Jupiter',choices:['Jupiter','Mars','Earth','Venus']},
{id:'s002',mode:'mixed',icon:'🫁',category:'SCIENCE',q:'Which organs help your body take oxygen from the air?',a:'Lungs',choices:['Lungs','Kidneys','Stomach','Bones']},
{id:'s003',mode:'mixed',icon:'💧',category:'SCIENCE',q:'At normal atmospheric pressure, water freezes at what temperature on the Celsius scale?',a:'0°C',choices:['0°C','10°C','32°C','100°C']},
{id:'s004',mode:'mixed',icon:'🌱',category:'SCIENCE',q:'What process do green plants use to make food using light?',a:'Photosynthesis',choices:['Photosynthesis','Respiration','Evaporation','Digestion']},
{id:'s005',mode:'mixed',icon:'⚡',category:'SCIENCE',q:'Which material is generally a good electrical conductor?',a:'Copper',choices:['Copper','Rubber','Dry wood','Plastic']},
{id:'s006',mode:'mixed',icon:'🧲',category:'SCIENCE',q:'A magnet has two main poles. What are they called?',a:'North and south',choices:['North and south','East and west','Positive and negative only','Top and bottom']},
{id:'s007',mode:'mixed',icon:'🦴',category:'SCIENCE',q:'What is the main job of your skeleton?',a:'Support and protect the body',choices:['Support and protect the body','Digest food','Pump blood','Create sound']},
{id:'s008',mode:'mixed',icon:'🌙',category:'SCIENCE',q:'Why does the Moon appear to change shape during the month?',a:'We see different sunlit portions as it orbits Earth',choices:['We see different sunlit portions as it orbits Earth','The Moon physically changes shape','Clouds permanently cover parts of it','Earth changes the Moon’s colour']},
{id:'s009',mode:'mixed',icon:'🌡️',category:'SCIENCE',q:'Which instrument is used to measure temperature?',a:'Thermometer',choices:['Thermometer','Barometer','Compass','Stopwatch']},
{id:'s010',mode:'mixed',icon:'🔊',category:'SCIENCE',q:'Sound needs what to travel through?',a:'A medium such as air, water or solids',choices:['A medium such as air, water or solids','Only empty space','Only light','Only metal']},
{id:'l001',mode:'mixed',icon:'💷',category:'LIFE',q:'You have £20 and spend £7.50. How much remains?',a:'£12.50',choices:['£12.50','£13.50','£11.50','£14.50']},
{id:'l002',mode:'mixed',icon:'🛒',category:'LIFE',q:'When comparing two packs of the same food, what can help you judge which is better value?',a:'Compare price and quantity/unit price',choices:['Compare price and quantity/unit price','Choose the brightest packaging','Choose the largest logo','Choose the one nearest the door']},
{id:'l003',mode:'mixed',icon:'🛡️',category:'SAFETY',q:'A stranger online asks which school you attend. What is the safest response?',a:'Do not share it and tell a trusted adult if concerned',choices:['Do not share it and tell a trusted adult if concerned','Tell them the school name only','Send a photo of the school','Ask for their school first']},
{id:'l004',mode:'mixed',icon:'🔐',category:'SAFETY',q:'Which password is generally strongest?',a:'A long unique passphrase',choices:['A long unique passphrase','password123','Your first name','12345678']},
{id:'l005',mode:'mixed',icon:'📨',category:'SAFETY',q:'A message says “You won a phone — click now and enter your password.” What should you do?',a:'Treat it as suspicious and do not enter your password',choices:['Treat it as suspicious and do not enter your password','Click quickly before the offer ends','Send your password to check','Forward it to everyone']},
{id:'l006',mode:'mixed',icon:'🚌',category:'LIFE',q:'A bus journey takes 35 minutes and you need to arrive by 09:00. Ignoring extra buffer time, what is the latest departure time?',a:'08:25',choices:['08:25','08:35','08:15','09:35']},
{id:'l007',mode:'mixed',icon:'🤝',category:'LIFE',q:'A good first step when a friend disagrees with you is usually to do what?',a:'Listen and explain calmly',choices:['Listen and explain calmly','Shout louder','Spread a rumour','Ignore them forever']},
{id:'l008',mode:'mixed',icon:'🧾',category:'LIFE',q:'What does a budget help you do?',a:'Plan how money will be used',choices:['Plan how money will be used','Make all prices cheaper','Guarantee more money','Avoid every unexpected cost']},
{id:'l009',mode:'mixed',icon:'🚨',category:'SAFETY',q:'In the UK, which number can be used for emergency services?',a:'999',choices:['999','123','555','1010']},
{id:'l010',mode:'mixed',icon:'🧠',category:'LIFE',q:'If you make a mistake during a challenge, which response is most useful?',a:'Work out what went wrong and try again',choices:['Work out what went wrong and try again','Pretend it never happened','Quit every similar task','Blame someone immediately']},
{id:'u001',mode:'mixed',icon:'🇬🇧',category:'MY UK',q:'The United Kingdom is made up of how many countries?',a:'Four',choices:['Four','Two','Five','Six']},
{id:'u002',mode:'mixed',icon:'🏛️',category:'MY UK',q:'Which institution debates and makes UK laws at national level?',a:'Parliament',choices:['Parliament','The weather service','A supermarket','A football league']},
{id:'u003',mode:'mixed',icon:'🤖',category:'TECH',q:'Why should you check an AI answer rather than trust it automatically?',a:'AI can make mistakes or invent details',choices:['AI can make mistakes or invent details','AI is always trying to lie','AI cannot produce any useful information','Checking is only needed for maths']},
{id:'u004',mode:'mixed',icon:'🌐',category:'TECH',q:'What is phishing?',a:'An attempt to trick people into revealing information or clicking harmful links',choices:['An attempt to trick people into revealing information or clicking harmful links','A way to improve Wi-Fi speed','A type of computer screen','A safe password manager']},
{id:'u005',mode:'mixed',icon:'💼',category:'FUTURE',q:'Revenue means what in a simple business example?',a:'Money the business receives from sales before costs are subtracted',choices:['Money the business receives from sales before costs are subtracted','Only the business profit','Money paid only in tax','The number of workers']}
];
window.JAPAN_QUESTIONS=[
{id:'j1',q:'What is the capital of Japan?',a:'Tokyo',choices:['Tokyo','Kyoto','Osaka','Sapporo']},
{id:'j2',q:'What currency is used in Japan?',a:'Yen',choices:['Yen','Won','Euro','Dollar']},
{id:'j3',q:'Mount Fuji is best described as what?',a:'A volcano and mountain',choices:['A volcano and mountain','A river','A city','An island']},
{id:'j4',q:'Which transport is the Shinkansen?',a:'High-speed train',choices:['High-speed train','Ferry','Cable car','Airship']},
{id:'j5',q:'Which writing systems are used in Japanese?',a:'Kanji, hiragana and katakana',choices:['Kanji, hiragana and katakana','Only the Latin alphabet','Only hieroglyphics','Only Cyrillic']}
];
