(function(){
  if(!window.CWState)return;
  const state=CWState.load(), access=window.CWAccess?CWAccess.get():{}, li=CWState.levelInfo();
  const set=(id,val)=>{const e=document.getElementById(id);if(e)e.textContent=val};
  set('pCountries',state.passport.length);set('pXp',li.xp.toLocaleString());set('pCompleted',Object.keys(state.completed||{}).length);set('pAchievements',state.achievements.length);
  set('pChildName',access.childNickname||'Explorer');set('pChildAvatar',access.childAvatar||'🦊');set('pChildMeta',`Age band ${access.childAge||'not set'} • Level ${li.level}`);set('pChildXp',`${li.xp.toLocaleString()} XP`);
  const bar=document.getElementById('pChildXpBar');if(bar)bar.style.width=li.percent+'%';
  const list=document.getElementById('parentActivityList');if(list){const recent=(state.recent||[]).slice(0,8);if(recent.length)list.innerHTML=recent.map(x=>`<div><span class="activity-icon">${x.icon||'✨'}</span><div><b>${x.title||'Activity'}</b><small>${x.detail||'Activity recorded'}</small></div><span>${friendlyTime(x.time)}</span></div>`).join('')}
  function friendlyTime(ts){const mins=Math.max(0,Math.floor((Date.now()-Number(ts||Date.now()))/60000));if(mins<1)return'Now';if(mins<60)return mins+'m ago';const h=Math.floor(mins/60);if(h<24)return h+'h ago';return Math.floor(h/24)+'d ago'}
  const form=document.getElementById('parentFeedbackForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();const type=document.getElementById('feedbackType').value,msg=document.getElementById('feedbackMessage').value.trim();if(!msg)return;CWState.addFeedback({type,message:msg,from:access.parentEmail||'Prototype parent'});document.getElementById('feedbackResult').innerHTML='<div class="feedback-success">✓ Feedback saved in the prototype inbox on this device. The production version will send it securely to Admin Studio.</div>';form.reset();CWState.logActivity({id:'parent-feedback',title:'Parent feedback sent',icon:'💬',detail:type,href:'parent.html'})});
  const manage=document.getElementById('pManageChild');if(manage)manage.onclick=()=>location.href='family-setup.html';

  // Curriculum-age access is parent-controlled and stored separately from Challenge progress.
  const childKey=String(access.childId||`${access.childNickname||'Explorer'}|${access.childAge||'10'}|${access.childAvatar||''}`),defaultAge=Math.max(10,Math.min(13,parseInt(String(access.childAge||'10').match(/\d+/)?.[0]||'10',10)||10)),KEY='cw_curriculum_access_v1';
  let root={};try{root=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(_){root={}}root.children=root.children||{};let row=root.children[childKey]||{defaultAge,unlockedAges:[defaultAge]};const unlocked=new Set((row.unlockedAges||[]).map(Number));unlocked.add(defaultAge);
  const host=document.getElementById('primaryChildRow')?.closest('.parent-panel');if(host&&!document.getElementById('curriculumAgeAccess')){const box=document.createElement('div');box.id='curriculumAgeAccess';box.className='membership-card';box.style.marginTop='18px';box.innerHTML=`<b>Curriculum age access</b><small style="display:block;margin:6px 0 10px">The child’s age sets the default. You can unlock additional curriculum ages without deleting any existing progress.</small><div id="curriculumAgeChecks" style="display:flex;gap:14px;flex-wrap:wrap"></div><small id="curriculumAgeSaved" style="display:block;margin-top:8px"></small>`;host.appendChild(box);const checks=box.querySelector('#curriculumAgeChecks');for(let age=10;age<=13;age++){const lab=document.createElement('label');lab.style.display='flex';lab.style.gap='6px';lab.style.alignItems='center';lab.innerHTML=`<input type="checkbox" value="${age}" ${unlocked.has(age)?'checked':''} ${age===defaultAge?'disabled':''}> Age ${age}${age===defaultAge?' (default)':''}`;checks.appendChild(lab)}checks.onchange=()=>{const ages=[...checks.querySelectorAll('input:checked')].map(x=>Number(x.value));if(!ages.includes(defaultAge))ages.push(defaultAge);root.children[childKey]={defaultAge,unlockedAges:[...new Set(ages)].sort((a,b)=>a-b),updatedAt:Date.now()};localStorage.setItem(KEY,JSON.stringify(root));box.querySelector('#curriculumAgeSaved').textContent='✓ Access updated. Existing Challenge progress was not changed.'}}
})();
